# 1. Dataset Loading

In this section, we load all raw M5 forecasting datasets using project-relative paths so that the notebook can run on any team member's system.

In [1]:
import os

print(os.getcwd())

c:\Users\priya\Downloads\retail-demand-forecasting\notebooks

In [2]:
import os

print(os.listdir("../data/raw"))

['.gitkeep', 'calendar.csv', 'sales_train_evaluation.csv', 'sales_train_validation.csv', 'sample_submission.csv', 'sell_prices.csv']

In [4]:
import pandas as pd
import os

# Set paths relative to the notebook location
base_path = "../data/raw"

calendar_path = os.path.join(base_path, "calendar.csv")
sell_prices_path = os.path.join(base_path, "sell_prices.csv")
sales_train_path = os.path.join(base_path, "sales_train_evaluation.csv")
sales_train_val_path = os.path.join(base_path,"sales_train_validation.csv")
sample_path = os.path.join(base_path,"sample_submission.csv")

# Load datasets
calendar = pd.read_csv(calendar_path)
sell_prices = pd.read_csv(sell_prices_path)
sales = pd.read_csv(sales_train_path)
sales_val = pd.read_csv(sales_train_val_path)
sample = pd.read_csv(sample_path)

print("Datasets loaded successfully!")

Datasets loaded successfully!

# 2. Dataset Structure

In this section, we examine the structure of each dataset, including the number of rows and columns, column names, data types, and a sample of the data.

In [5]:
datasets = {
    "Calendar": calendar,
    "Sell Prices": sell_prices,
    "Sales Train Evaluation": sales,
    "sales train validation": sales_val,
    "sample submission": sample

}

for name, df in datasets.items():
    print("=" * 50)
    print(f"{name} Dataset")
    print("=" * 50)
    
    print("Shape:", df.shape)
    
    print("\nColumn Names:")
    print(df.columns.tolist())
    
    print("\nData Types:")
    print(df.dtypes)
    
    print("\nFirst 5 Rows:")
    display(df.head())
    
    print("\n")

==================================================
Calendar Dataset
==================================================
Shape: (1969, 14)

Column Names:
['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

Data Types:
date              str
wm_yr_wk        int64
weekday           str
wday            int64
month           int64
year            int64
d                 str
event_name_1      str
event_type_1      str
event_name_2      str
event_type_2      str
snap_CA         int64
snap_TX         int64
snap_WI         int64
dtype: object

First 5 Rows:

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

==================================================
Sell Prices Dataset
==================================================
Shape: (6841121, 4)

Column Names:
['store_id', 'item_id', 'wm_yr_wk', 'sell_price']

Data Types:
store_id          str
item_id           str
wm_yr_wk        int64
sell_price    float64
dtype: object

First 5 Rows:

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

==================================================
Sales Train Evaluation Dataset
==================================================
Shape: (30490, 1947)

Column Names:
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9', 'd_10', 'd_11', 'd_12', 'd_13', 'd_14', 'd_15', 'd_16', 'd_17', 'd_18', 'd_19', 'd_20', 'd_21', 'd_22', 'd_23', 'd_24', 'd_25', 'd_26', 'd_27', 'd_28', 'd_29', 'd_30', 'd_31', 'd_32', 'd_33', 'd_34', 'd_35', 'd_36', 'd_37', 'd_38', 'd_39', 'd_40', 'd_41', 'd_42', 'd_43', 'd_44', 'd_45', 'd_46', 'd_47', 'd_48', 'd_49', 'd_50', 'd_51', 'd_52', 'd_53', 'd_54', 'd_55', 'd_56', 'd_57', 'd_58', 'd_59', 'd_60', 'd_61', 'd_62', 'd_63', 'd_64', 'd_65', 'd_66', 'd_67', 'd_68', 'd_69', 'd_70', 'd_71', 'd_72', 'd_73', 'd_74', 'd_75', 'd_76', 'd_77', 'd_78', 'd_79', 'd_80', 'd_81', 'd_82', 'd_83', 'd_84', 'd_85', 'd_86', 'd_87', 'd_88', 'd_89', 'd_90', 'd_91', 'd_92', 'd_93', 'd_94', 'd_95', 'd_96', 'd_97', 'd_98', 'd_99', 'd_100', 'd_101', 'd_102', 'd_103', 'd_104', 'd_105', 'd_106', 'd_107', 'd_108', 'd_109', 'd_110', 'd_111', 'd_112', 'd_113', 'd_114', 'd_115', 'd_116', 'd_117', 'd_118', 'd_119', 'd_120', 'd_121', 'd_122', 'd_123', 'd_124', 'd_125', 'd_126', 'd_127', 'd_128', 'd_129', 'd_130', 'd_131', 'd_132', 'd_133', 'd_134', 'd_135', 'd_136', 'd_137', 'd_138', 'd_139', 'd_140', 'd_141', 'd_142', 'd_143', 'd_144', 'd_145', 'd_146', 'd_147', 'd_148', 'd_149', 'd_150', 'd_151', 'd_152', 'd_153', 'd_154', 'd_155', 'd_156', 'd_157', 'd_158', 'd_159', 'd_160', 'd_161', 'd_162', 'd_163', 'd_164', 'd_165', 'd_166', 'd_167', 'd_168', 'd_169', 'd_170', 'd_171', 'd_172', 'd_173', 'd_174', 'd_175', 'd_176', 'd_177', 'd_178', 'd_179', 'd_180', 'd_181', 'd_182', 'd_183', 'd_184', 'd_185', 'd_186', 'd_187', 'd_188', 'd_189', 'd_190', 'd_191', 'd_192', 'd_193', 'd_194', 'd_195', 'd_196', 'd_197', 'd_198', 'd_199', 'd_200', 'd_201', 'd_202', 'd_203', 'd_204', 'd_205', 'd_206', 'd_207', 'd_208', 'd_209', 'd_210', 'd_211', 'd_212', 'd_213', 'd_214', 'd_215', 'd_216', 'd_217', 'd_218', 'd_219', 'd_220', 'd_221', 'd_222', 'd_223', 'd_224', 'd_225', 'd_226', 'd_227', 'd_228', 'd_229', 'd_230', 'd_231', 'd_232', 'd_233', 'd_234', 'd_235', 'd_236', 'd_237', 'd_238', 'd_239', 'd_240', 'd_241', 'd_242', 'd_243', 'd_244', 'd_245', 'd_246', 'd_247', 'd_248', 'd_249', 'd_250', 'd_251', 'd_252', 'd_253', 'd_254', 'd_255', 'd_256', 'd_257', 'd_258', 'd_259', 'd_260', 'd_261', 'd_262', 'd_263', 'd_264', 'd_265', 'd_266', 'd_267', 'd_268', 'd_269', 'd_270', 'd_271', 'd_272', 'd_273', 'd_274', 'd_275', 'd_276', 'd_277', 'd_278', 'd_279', 'd_280', 'd_281', 'd_282', 'd_283', 'd_284', 'd_285', 'd_286', 'd_287', 'd_288', 'd_289', 'd_290', 'd_291', 'd_292', 'd_293', 'd_294', 'd_295', 'd_296', 'd_297', 'd_298', 'd_299', 'd_300', 'd_301', 'd_302', 'd_303', 'd_304', 'd_305', 'd_306', 'd_307', 'd_308', 'd_309', 'd_310', 'd_311', 'd_312', 'd_313', 'd_314', 'd_315', 'd_316', 'd_317', 'd_318', 'd_319', 'd_320', 'd_321', 'd_322', 'd_323', 'd_324', 'd_325', 'd_326', 'd_327', 'd_328', 'd_329', 'd_330', 'd_331', 'd_332', 'd_333', 'd_334', 'd_335', 'd_336', 'd_337', 'd_338', 'd_339', 'd_340', 'd_341', 'd_342', 'd_343', 'd_344', 'd_345', 'd_346', 'd_347', 'd_348', 'd_349', 'd_350', 'd_351', 'd_352', 'd_353', 'd_354', 'd_355', 'd_356', 'd_357', 'd_358', 'd_359', 'd_360', 'd_361', 'd_362', 'd_363', 'd_364', 'd_365', 'd_366', 'd_367', 'd_368', 'd_369', 'd_370', 'd_371', 'd_372', 'd_373', 'd_374', 'd_375', 'd_376', 'd_377', 'd_378', 'd_379', 'd_380', 'd_381', 'd_382', 'd_383', 'd_384', 'd_385', 'd_386', 'd_387', 'd_388', 'd_389', 'd_390', 'd_391', 'd_392', 'd_393', 'd_394', 'd_395', 'd_396', 'd_397', 'd_398', 'd_399', 'd_400', 'd_401', 'd_402', 'd_403', 'd_404', 'd_405', 'd_406', 'd_407', 'd_408', 'd_409', 'd_410', 'd_411', 'd_412', 'd_413', 'd_414', 'd_415', 'd_416', 'd_417', 'd_418', 'd_419', 'd_420', 'd_421', 'd_422', 'd_423', 'd_424', 'd_425', 'd_426', 'd_427', 'd_428', 'd_429', 'd_430', 'd_431', 'd_432', 'd_433', 'd_434', 'd_435', 'd_436', 'd_437', 'd_438', 'd_439', 'd_440', 'd_441', 'd_442', 'd_443', 'd_444', 'd_445', 'd_446', 'd_447', 'd_448', 'd_449', 'd_450', 'd_451', 'd_452', 'd_453', 'd_454', 'd_455', 'd_456', 'd_457', 'd_458', 'd_459', 'd_460', 'd_461', 'd_462', 'd_463', 'd_464', 'd_465', 'd_466', 'd_467', 'd_468', 'd_469', 'd_470', 'd_471', 'd_472', 'd_473', 'd_474', 'd_475', 'd_476', 'd_477', 'd_478', 'd_479', 'd_480', 'd_481', 'd_482', 'd_483', 'd_484', 'd_485', 'd_486', 'd_487', 'd_488', 'd_489', 'd_490', 'd_491', 'd_492', 'd_493', 'd_494', 'd_495', 'd_496', 'd_497', 'd_498', 'd_499', 'd_500', 'd_501', 'd_502', 'd_503', 'd_504', 'd_505', 'd_506', 'd_507', 'd_508', 'd_509', 'd_510', 'd_511', 'd_512', 'd_513', 'd_514', 'd_515', 'd_516', 'd_517', 'd_518', 'd_519', 'd_520', 'd_521', 'd_522', 'd_523', 'd_524', 'd_525', 'd_526', 'd_527', 'd_528', 'd_529', 'd_530', 'd_531', 'd_532', 'd_533', 'd_534', 'd_535', 'd_536', 'd_537', 'd_538', 'd_539', 'd_540', 'd_541', 'd_542', 'd_543', 'd_544', 'd_545', 'd_546', 'd_547', 'd_548', 'd_549', 'd_550', 'd_551', 'd_552', 'd_553', 'd_554', 'd_555', 'd_556', 'd_557', 'd_558', 'd_559', 'd_560', 'd_561', 'd_562', 'd_563', 'd_564', 'd_565', 'd_566', 'd_567', 'd_568', 'd_569', 'd_570', 'd_571', 'd_572', 'd_573', 'd_574', 'd_575', 'd_576', 'd_577', 'd_578', 'd_579', 'd_580', 'd_581', 'd_582', 'd_583', 'd_584', 'd_585', 'd_586', 'd_587', 'd_588', 'd_589', 'd_590', 'd_591', 'd_592', 'd_593', 'd_594', 'd_595', 'd_596', 'd_597', 'd_598', 'd_599', 'd_600', 'd_601', 'd_602', 'd_603', 'd_604', 'd_605', 'd_606', 'd_607', 'd_608', 'd_609', 'd_610', 'd_611', 'd_612', 'd_613', 'd_614', 'd_615', 'd_616', 'd_617', 'd_618', 'd_619', 'd_620', 'd_621', 'd_622', 'd_623', 'd_624', 'd_625', 'd_626', 'd_627', 'd_628', 'd_629', 'd_630', 'd_631', 'd_632', 'd_633', 'd_634', 'd_635', 'd_636', 'd_637', 'd_638', 'd_639', 'd_640', 'd_641', 'd_642', 'd_643', 'd_644', 'd_645', 'd_646', 'd_647', 'd_648', 'd_649', 'd_650', 'd_651', 'd_652', 'd_653', 'd_654', 'd_655', 'd_656', 'd_657', 'd_658', 'd_659', 'd_660', 'd_661', 'd_662', 'd_663', 'd_664', 'd_665', 'd_666', 'd_667', 'd_668', 'd_669', 'd_670', 'd_671', 'd_672', 'd_673', 'd_674', 'd_675', 'd_676', 'd_677', 'd_678', 'd_679', 'd_680', 'd_681', 'd_682', 'd_683', 'd_684', 'd_685', 'd_686', 'd_687', 'd_688', 'd_689', 'd_690', 'd_691', 'd_692', 'd_693', 'd_694', 'd_695', 'd_696', 'd_697', 'd_698', 'd_699', 'd_700', 'd_701', 'd_702', 'd_703', 'd_704', 'd_705', 'd_706', 'd_707', 'd_708', 'd_709', 'd_710', 'd_711', 'd_712', 'd_713', 'd_714', 'd_715', 'd_716', 'd_717', 'd_718', 'd_719', 'd_720', 'd_721', 'd_722', 'd_723', 'd_724', 'd_725', 'd_726', 'd_727', 'd_728', 'd_729', 'd_730', 'd_731', 'd_732', 'd_733', 'd_734', 'd_735', 'd_736', 'd_737', 'd_738', 'd_739', 'd_740', 'd_741', 'd_742', 'd_743', 'd_744', 'd_745', 'd_746', 'd_747', 'd_748', 'd_749', 'd_750', 'd_751', 'd_752', 'd_753', 'd_754', 'd_755', 'd_756', 'd_757', 'd_758', 'd_759', 'd_760', 'd_761', 'd_762', 'd_763', 'd_764', 'd_765', 'd_766', 'd_767', 'd_768', 'd_769', 'd_770', 'd_771', 'd_772', 'd_773', 'd_774', 'd_775', 'd_776', 'd_777', 'd_778', 'd_779', 'd_780', 'd_781', 'd_782', 'd_783', 'd_784', 'd_785', 'd_786', 'd_787', 'd_788', 'd_789', 'd_790', 'd_791', 'd_792', 'd_793', 'd_794', 'd_795', 'd_796', 'd_797', 'd_798', 'd_799', 'd_800', 'd_801', 'd_802', 'd_803', 'd_804', 'd_805', 'd_806', 'd_807', 'd_808', 'd_809', 'd_810', 'd_811', 'd_812', 'd_813', 'd_814', 'd_815', 'd_816', 'd_817', 'd_818', 'd_819', 'd_820', 'd_821', 'd_822', 'd_823', 'd_824', 'd_825', 'd_826', 'd_827', 'd_828', 'd_829', 'd_830', 'd_831', 'd_832', 'd_833', 'd_834', 'd_835', 'd_836', 'd_837', 'd_838', 'd_839', 'd_840', 'd_841', 'd_842', 'd_843', 'd_844', 'd_845', 'd_846', 'd_847', 'd_848', 'd_849', 'd_850', 'd_851', 'd_852', 'd_853', 'd_854', 'd_855', 'd_856', 'd_857', 'd_858', 'd_859', 'd_860', 'd_861', 'd_862', 'd_863', 'd_864', 'd_865', 'd_866', 'd_867', 'd_868', 'd_869', 'd_870', 'd_871', 'd_872', 'd_873', 'd_874', 'd_875', 'd_876', 'd_877', 'd_878', 'd_879', 'd_880', 'd_881', 'd_882', 'd_883', 'd_884', 'd_885', 'd_886', 'd_887', 'd_888', 'd_889', 'd_890', 'd_891', 'd_892', 'd_893', 'd_894', 'd_895', 'd_896', 'd_897', 'd_898', 'd_899', 'd_900', 'd_901', 'd_902', 'd_903', 'd_904', 'd_905', 'd_906', 'd_907', 'd_908', 'd_909', 'd_910', 'd_911', 'd_912', 'd_913', 'd_914', 'd_915', 'd_916', 'd_917', 'd_918', 'd_919', 'd_920', 'd_921', 'd_922', 'd_923', 'd_924', 'd_925', 'd_926', 'd_927', 'd_928', 'd_929', 'd_930', 'd_931', 'd_932', 'd_933', 'd_934', 'd_935', 'd_936', 'd_937', 'd_938', 'd_939', 'd_940', 'd_941', 'd_942', 'd_943', 'd_944', 'd_945', 'd_946', 'd_947', 'd_948', 'd_949', 'd_950', 'd_951', 'd_952', 'd_953', 'd_954', 'd_955', 'd_956', 'd_957', 'd_958', 'd_959', 'd_960', 'd_961', 'd_962', 'd_963', 'd_964', 'd_965', 'd_966', 'd_967', 'd_968', 'd_969', 'd_970', 'd_971', 'd_972', 'd_973', 'd_974', 'd_975', 'd_976', 'd_977', 'd_978', 'd_979', 'd_980', 'd_981', 'd_982', 'd_983', 'd_984', 'd_985', 'd_986', 'd_987', 'd_988', 'd_989', 'd_990', 'd_991', 'd_992', 'd_993', 'd_994', 'd_995', 'd_996', 'd_997', 'd_998', 'd_999', 'd_1000', 'd_1001', 'd_1002', 'd_1003', 'd_1004', 'd_1005', 'd_1006', 'd_1007', 'd_1008', 'd_1009', 'd_1010', 'd_1011', 'd_1012', 'd_1013', 'd_1014', 'd_1015', 'd_1016', 'd_1017', 'd_1018', 'd_1019', 'd_1020', 'd_1021', 'd_1022', 'd_1023', 'd_1024', 'd_1025', 'd_1026', 'd_1027', 'd_1028', 'd_1029', 'd_1030', 'd_1031', 'd_1032', 'd_1033', 'd_1034', 'd_1035', 'd_1036', 'd_1037', 'd_1038', 'd_1039', 'd_1040', 'd_1041', 'd_1042', 'd_1043', 'd_1044', 'd_1045', 'd_1046', 'd_1047', 'd_1048', 'd_1049', 'd_1050', 'd_1051', 'd_1052', 'd_1053', 'd_1054', 'd_1055', 'd_1056', 'd_1057', 'd_1058', 'd_1059', 'd_1060', 'd_1061', 'd_1062', 'd_1063', 'd_1064', 'd_1065', 'd_1066', 'd_1067', 'd_1068', 'd_1069', 'd_1070', 'd_1071', 'd_1072', 'd_1073', 'd_1074', 'd_1075', 'd_1076', 'd_1077', 'd_1078', 'd_1079', 'd_1080', 'd_1081', 'd_1082', 'd_1083', 'd_1084', 'd_1085', 'd_1086', 'd_1087', 'd_1088', 'd_1089', 'd_1090', 'd_1091', 'd_1092', 'd_1093', 'd_1094', 'd_1095', 'd_1096', 'd_1097', 'd_1098', 'd_1099', 'd_1100', 'd_1101', 'd_1102', 'd_1103', 'd_1104', 'd_1105', 'd_1106', 'd_1107', 'd_1108', 'd_1109', 'd_1110', 'd_1111', 'd_1112', 'd_1113', 'd_1114', 'd_1115', 'd_1116', 'd_1117', 'd_1118', 'd_1119', 'd_1120', 'd_1121', 'd_1122', 'd_1123', 'd_1124', 'd_1125', 'd_1126', 'd_1127', 'd_1128', 'd_1129', 'd_1130', 'd_1131', 'd_1132', 'd_1133', 'd_1134', 'd_1135', 'd_1136', 'd_1137', 'd_1138', 'd_1139', 'd_1140', 'd_1141', 'd_1142', 'd_1143', 'd_1144', 'd_1145', 'd_1146', 'd_1147', 'd_1148', 'd_1149', 'd_1150', 'd_1151', 'd_1152', 'd_1153', 'd_1154', 'd_1155', 'd_1156', 'd_1157', 'd_1158', 'd_1159', 'd_1160', 'd_1161', 'd_1162', 'd_1163', 'd_1164', 'd_1165', 'd_1166', 'd_1167', 'd_1168', 'd_1169', 'd_1170', 'd_1171', 'd_1172', 'd_1173', 'd_1174', 'd_1175', 'd_1176', 'd_1177', 'd_1178', 'd_1179', 'd_1180', 'd_1181', 'd_1182', 'd_1183', 'd_1184', 'd_1185', 'd_1186', 'd_1187', 'd_1188', 'd_1189', 'd_1190', 'd_1191', 'd_1192', 'd_1193', 'd_1194', 'd_1195', 'd_1196', 'd_1197', 'd_1198', 'd_1199', 'd_1200', 'd_1201', 'd_1202', 'd_1203', 'd_1204', 'd_1205', 'd_1206', 'd_1207', 'd_1208', 'd_1209', 'd_1210', 'd_1211', 'd_1212', 'd_1213', 'd_1214', 'd_1215', 'd_1216', 'd_1217', 'd_1218', 'd_1219', 'd_1220', 'd_1221', 'd_1222', 'd_1223', 'd_1224', 'd_1225', 'd_1226', 'd_1227', 'd_1228', 'd_1229', 'd_1230', 'd_1231', 'd_1232', 'd_1233', 'd_1234', 'd_1235', 'd_1236', 'd_1237', 'd_1238', 'd_1239', 'd_1240', 'd_1241', 'd_1242', 'd_1243', 'd_1244', 'd_1245', 'd_1246', 'd_1247', 'd_1248', 'd_1249', 'd_1250', 'd_1251', 'd_1252', 'd_1253', 'd_1254', 'd_1255', 'd_1256', 'd_1257', 'd_1258', 'd_1259', 'd_1260', 'd_1261', 'd_1262', 'd_1263', 'd_1264', 'd_1265', 'd_1266', 'd_1267', 'd_1268', 'd_1269', 'd_1270', 'd_1271', 'd_1272', 'd_1273', 'd_1274', 'd_1275', 'd_1276', 'd_1277', 'd_1278', 'd_1279', 'd_1280', 'd_1281', 'd_1282', 'd_1283', 'd_1284', 'd_1285', 'd_1286', 'd_1287', 'd_1288', 'd_1289', 'd_1290', 'd_1291', 'd_1292', 'd_1293', 'd_1294', 'd_1295', 'd_1296', 'd_1297', 'd_1298', 'd_1299', 'd_1300', 'd_1301', 'd_1302', 'd_1303', 'd_1304', 'd_1305', 'd_1306', 'd_1307', 'd_1308', 'd_1309', 'd_1310', 'd_1311', 'd_1312', 'd_1313', 'd_1314', 'd_1315', 'd_1316', 'd_1317', 'd_1318', 'd_1319', 'd_1320', 'd_1321', 'd_1322', 'd_1323', 'd_1324', 'd_1325', 'd_1326', 'd_1327', 'd_1328', 'd_1329', 'd_1330', 'd_1331', 'd_1332', 'd_1333', 'd_1334', 'd_1335', 'd_1336', 'd_1337', 'd_1338', 'd_1339', 'd_1340', 'd_1341', 'd_1342', 'd_1343', 'd_1344', 'd_1345', 'd_1346', 'd_1347', 'd_1348', 'd_1349', 'd_1350', 'd_1351', 'd_1352', 'd_1353', 'd_1354', 'd_1355', 'd_1356', 'd_1357', 'd_1358', 'd_1359', 'd_1360', 'd_1361', 'd_1362', 'd_1363', 'd_1364', 'd_1365', 'd_1366', 'd_1367', 'd_1368', 'd_1369', 'd_1370', 'd_1371', 'd_1372', 'd_1373', 'd_1374', 'd_1375', 'd_1376', 'd_1377', 'd_1378', 'd_1379', 'd_1380', 'd_1381', 'd_1382', 'd_1383', 'd_1384', 'd_1385', 'd_1386', 'd_1387', 'd_1388', 'd_1389', 'd_1390', 'd_1391', 'd_1392', 'd_1393', 'd_1394', 'd_1395', 'd_1396', 'd_1397', 'd_1398', 'd_1399', 'd_1400', 'd_1401', 'd_1402', 'd_1403', 'd_1404', 'd_1405', 'd_1406', 'd_1407', 'd_1408', 'd_1409', 'd_1410', 'd_1411', 'd_1412', 'd_1413', 'd_1414', 'd_1415', 'd_1416', 'd_1417', 'd_1418', 'd_1419', 'd_1420', 'd_1421', 'd_1422', 'd_1423', 'd_1424', 'd_1425', 'd_1426', 'd_1427', 'd_1428', 'd_1429', 'd_1430', 'd_1431', 'd_1432', 'd_1433', 'd_1434', 'd_1435', 'd_1436', 'd_1437', 'd_1438', 'd_1439', 'd_1440', 'd_1441', 'd_1442', 'd_1443', 'd_1444', 'd_1445', 'd_1446', 'd_1447', 'd_1448', 'd_1449', 'd_1450', 'd_1451', 'd_1452', 'd_1453', 'd_1454', 'd_1455', 'd_1456', 'd_1457', 'd_1458', 'd_1459', 'd_1460', 'd_1461', 'd_1462', 'd_1463', 'd_1464', 'd_1465', 'd_1466', 'd_1467', 'd_1468', 'd_1469', 'd_1470', 'd_1471', 'd_1472', 'd_1473', 'd_1474', 'd_1475', 'd_1476', 'd_1477', 'd_1478', 'd_1479', 'd_1480', 'd_1481', 'd_1482', 'd_1483', 'd_1484', 'd_1485', 'd_1486', 'd_1487', 'd_1488', 'd_1489', 'd_1490', 'd_1491', 'd_1492', 'd_1493', 'd_1494', 'd_1495', 'd_1496', 'd_1497', 'd_1498', 'd_1499', 'd_1500', 'd_1501', 'd_1502', 'd_1503', 'd_1504', 'd_1505', 'd_1506', 'd_1507', 'd_1508', 'd_1509', 'd_1510', 'd_1511', 'd_1512', 'd_1513', 'd_1514', 'd_1515', 'd_1516', 'd_1517', 'd_1518', 'd_1519', 'd_1520', 'd_1521', 'd_1522', 'd_1523', 'd_1524', 'd_1525', 'd_1526', 'd_1527', 'd_1528', 'd_1529', 'd_1530', 'd_1531', 'd_1532', 'd_1533', 'd_1534', 'd_1535', 'd_1536', 'd_1537', 'd_1538', 'd_1539', 'd_1540', 'd_1541', 'd_1542', 'd_1543', 'd_1544', 'd_1545', 'd_1546', 'd_1547', 'd_1548', 'd_1549', 'd_1550', 'd_1551', 'd_1552', 'd_1553', 'd_1554', 'd_1555', 'd_1556', 'd_1557', 'd_1558', 'd_1559', 'd_1560', 'd_1561', 'd_1562', 'd_1563', 'd_1564', 'd_1565', 'd_1566', 'd_1567', 'd_1568', 'd_1569', 'd_1570', 'd_1571', 'd_1572', 'd_1573', 'd_1574', 'd_1575', 'd_1576', 'd_1577', 'd_1578', 'd_1579', 'd_1580', 'd_1581', 'd_1582', 'd_1583', 'd_1584', 'd_1585', 'd_1586', 'd_1587', 'd_1588', 'd_1589', 'd_1590', 'd_1591', 'd_1592', 'd_1593', 'd_1594', 'd_1595', 'd_1596', 'd_1597', 'd_1598', 'd_1599', 'd_1600', 'd_1601', 'd_1602', 'd_1603', 'd_1604', 'd_1605', 'd_1606', 'd_1607', 'd_1608', 'd_1609', 'd_1610', 'd_1611', 'd_1612', 'd_1613', 'd_1614', 'd_1615', 'd_1616', 'd_1617', 'd_1618', 'd_1619', 'd_1620', 'd_1621', 'd_1622', 'd_1623', 'd_1624', 'd_1625', 'd_1626', 'd_1627', 'd_1628', 'd_1629', 'd_1630', 'd_1631', 'd_1632', 'd_1633', 'd_1634', 'd_1635', 'd_1636', 'd_1637', 'd_1638', 'd_1639', 'd_1640', 'd_1641', 'd_1642', 'd_1643', 'd_1644', 'd_1645', 'd_1646', 'd_1647', 'd_1648', 'd_1649', 'd_1650', 'd_1651', 'd_1652', 'd_1653', 'd_1654', 'd_1655', 'd_1656', 'd_1657', 'd_1658', 'd_1659', 'd_1660', 'd_1661', 'd_1662', 'd_1663', 'd_1664', 'd_1665', 'd_1666', 'd_1667', 'd_1668', 'd_1669', 'd_1670', 'd_1671', 'd_1672', 'd_1673', 'd_1674', 'd_1675', 'd_1676', 'd_1677', 'd_1678', 'd_1679', 'd_1680', 'd_1681', 'd_1682', 'd_1683', 'd_1684', 'd_1685', 'd_1686', 'd_1687', 'd_1688', 'd_1689', 'd_1690', 'd_1691', 'd_1692', 'd_1693', 'd_1694', 'd_1695', 'd_1696', 'd_1697', 'd_1698', 'd_1699', 'd_1700', 'd_1701', 'd_1702', 'd_1703', 'd_1704', 'd_1705', 'd_1706', 'd_1707', 'd_1708', 'd_1709', 'd_1710', 'd_1711', 'd_1712', 'd_1713', 'd_1714', 'd_1715', 'd_1716', 'd_1717', 'd_1718', 'd_1719', 'd_1720', 'd_1721', 'd_1722', 'd_1723', 'd_1724', 'd_1725', 'd_1726', 'd_1727', 'd_1728', 'd_1729', 'd_1730', 'd_1731', 'd_1732', 'd_1733', 'd_1734', 'd_1735', 'd_1736', 'd_1737', 'd_1738', 'd_1739', 'd_1740', 'd_1741', 'd_1742', 'd_1743', 'd_1744', 'd_1745', 'd_1746', 'd_1747', 'd_1748', 'd_1749', 'd_1750', 'd_1751', 'd_1752', 'd_1753', 'd_1754', 'd_1755', 'd_1756', 'd_1757', 'd_1758', 'd_1759', 'd_1760', 'd_1761', 'd_1762', 'd_1763', 'd_1764', 'd_1765', 'd_1766', 'd_1767', 'd_1768', 'd_1769', 'd_1770', 'd_1771', 'd_1772', 'd_1773', 'd_1774', 'd_1775', 'd_1776', 'd_1777', 'd_1778', 'd_1779', 'd_1780', 'd_1781', 'd_1782', 'd_1783', 'd_1784', 'd_1785', 'd_1786', 'd_1787', 'd_1788', 'd_1789', 'd_1790', 'd_1791', 'd_1792', 'd_1793', 'd_1794', 'd_1795', 'd_1796', 'd_1797', 'd_1798', 'd_1799', 'd_1800', 'd_1801', 'd_1802', 'd_1803', 'd_1804', 'd_1805', 'd_1806', 'd_1807', 'd_1808', 'd_1809', 'd_1810', 'd_1811', 'd_1812', 'd_1813', 'd_1814', 'd_1815', 'd_1816', 'd_1817', 'd_1818', 'd_1819', 'd_1820', 'd_1821', 'd_1822', 'd_1823', 'd_1824', 'd_1825', 'd_1826', 'd_1827', 'd_1828', 'd_1829', 'd_1830', 'd_1831', 'd_1832', 'd_1833', 'd_1834', 'd_1835', 'd_1836', 'd_1837', 'd_1838', 'd_1839', 'd_1840', 'd_1841', 'd_1842', 'd_1843', 'd_1844', 'd_1845', 'd_1846', 'd_1847', 'd_1848', 'd_1849', 'd_1850', 'd_1851', 'd_1852', 'd_1853', 'd_1854', 'd_1855', 'd_1856', 'd_1857', 'd_1858', 'd_1859', 'd_1860', 'd_1861', 'd_1862', 'd_1863', 'd_1864', 'd_1865', 'd_1866', 'd_1867', 'd_1868', 'd_1869', 'd_1870', 'd_1871', 'd_1872', 'd_1873', 'd_1874', 'd_1875', 'd_1876', 'd_1877', 'd_1878', 'd_1879', 'd_1880', 'd_1881', 'd_1882', 'd_1883', 'd_1884', 'd_1885', 'd_1886', 'd_1887', 'd_1888', 'd_1889', 'd_1890', 'd_1891', 'd_1892', 'd_1893', 'd_1894', 'd_1895', 'd_1896', 'd_1897', 'd_1898', 'd_1899', 'd_1900', 'd_1901', 'd_1902', 'd_1903', 'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913', 'd_1914', 'd_1915', 'd_1916', 'd_1917', 'd_1918', 'd_1919', 'd_1920', 'd_1921', 'd_1922', 'd_1923', 'd_1924', 'd_1925', 'd_1926', 'd_1927', 'd_1928', 'd_1929', 'd_1930', 'd_1931', 'd_1932', 'd_1933', 'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938', 'd_1939', 'd_1940', 'd_1941']

Data Types:
id            str
item_id       str
dept_id       str
cat_id        str
store_id      str
            ...
d_1937      int64
d_1938      int64
d_1939      int64
d_1940      int64
d_1941      int64
Length: 1947, dtype: object

First 5 Rows:

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

==================================================
sales train validation Dataset
==================================================
Shape: (30490, 1919)

Column Names:
['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1', 'd_2', 'd_3', 'd_4', 'd_5', 'd_6', 'd_7', 'd_8', 'd_9', 'd_10', 'd_11', 'd_12', 'd_13', 'd_14', 'd_15', 'd_16', 'd_17', 'd_18', 'd_19', 'd_20', 'd_21', 'd_22', 'd_23', 'd_24', 'd_25', 'd_26', 'd_27', 'd_28', 'd_29', 'd_30', 'd_31', 'd_32', 'd_33', 'd_34', 'd_35', 'd_36', 'd_37', 'd_38', 'd_39', 'd_40', 'd_41', 'd_42', 'd_43', 'd_44', 'd_45', 'd_46', 'd_47', 'd_48', 'd_49', 'd_50', 'd_51', 'd_52', 'd_53', 'd_54', 'd_55', 'd_56', 'd_57', 'd_58', 'd_59', 'd_60', 'd_61', 'd_62', 'd_63', 'd_64', 'd_65', 'd_66', 'd_67', 'd_68', 'd_69', 'd_70', 'd_71', 'd_72', 'd_73', 'd_74', 'd_75', 'd_76', 'd_77', 'd_78', 'd_79', 'd_80', 'd_81', 'd_82', 'd_83', 'd_84', 'd_85', 'd_86', 'd_87', 'd_88', 'd_89', 'd_90', 'd_91', 'd_92', 'd_93', 'd_94', 'd_95', 'd_96', 'd_97', 'd_98', 'd_99', 'd_100', 'd_101', 'd_102', 'd_103', 'd_104', 'd_105', 'd_106', 'd_107', 'd_108', 'd_109', 'd_110', 'd_111', 'd_112', 'd_113', 'd_114', 'd_115', 'd_116', 'd_117', 'd_118', 'd_119', 'd_120', 'd_121', 'd_122', 'd_123', 'd_124', 'd_125', 'd_126', 'd_127', 'd_128', 'd_129', 'd_130', 'd_131', 'd_132', 'd_133', 'd_134', 'd_135', 'd_136', 'd_137', 'd_138', 'd_139', 'd_140', 'd_141', 'd_142', 'd_143', 'd_144', 'd_145', 'd_146', 'd_147', 'd_148', 'd_149', 'd_150', 'd_151', 'd_152', 'd_153', 'd_154', 'd_155', 'd_156', 'd_157', 'd_158', 'd_159', 'd_160', 'd_161', 'd_162', 'd_163', 'd_164', 'd_165', 'd_166', 'd_167', 'd_168', 'd_169', 'd_170', 'd_171', 'd_172', 'd_173', 'd_174', 'd_175', 'd_176', 'd_177', 'd_178', 'd_179', 'd_180', 'd_181', 'd_182', 'd_183', 'd_184', 'd_185', 'd_186', 'd_187', 'd_188', 'd_189', 'd_190', 'd_191', 'd_192', 'd_193', 'd_194', 'd_195', 'd_196', 'd_197', 'd_198', 'd_199', 'd_200', 'd_201', 'd_202', 'd_203', 'd_204', 'd_205', 'd_206', 'd_207', 'd_208', 'd_209', 'd_210', 'd_211', 'd_212', 'd_213', 'd_214', 'd_215', 'd_216', 'd_217', 'd_218', 'd_219', 'd_220', 'd_221', 'd_222', 'd_223', 'd_224', 'd_225', 'd_226', 'd_227', 'd_228', 'd_229', 'd_230', 'd_231', 'd_232', 'd_233', 'd_234', 'd_235', 'd_236', 'd_237', 'd_238', 'd_239', 'd_240', 'd_241', 'd_242', 'd_243', 'd_244', 'd_245', 'd_246', 'd_247', 'd_248', 'd_249', 'd_250', 'd_251', 'd_252', 'd_253', 'd_254', 'd_255', 'd_256', 'd_257', 'd_258', 'd_259', 'd_260', 'd_261', 'd_262', 'd_263', 'd_264', 'd_265', 'd_266', 'd_267', 'd_268', 'd_269', 'd_270', 'd_271', 'd_272', 'd_273', 'd_274', 'd_275', 'd_276', 'd_277', 'd_278', 'd_279', 'd_280', 'd_281', 'd_282', 'd_283', 'd_284', 'd_285', 'd_286', 'd_287', 'd_288', 'd_289', 'd_290', 'd_291', 'd_292', 'd_293', 'd_294', 'd_295', 'd_296', 'd_297', 'd_298', 'd_299', 'd_300', 'd_301', 'd_302', 'd_303', 'd_304', 'd_305', 'd_306', 'd_307', 'd_308', 'd_309', 'd_310', 'd_311', 'd_312', 'd_313', 'd_314', 'd_315', 'd_316', 'd_317', 'd_318', 'd_319', 'd_320', 'd_321', 'd_322', 'd_323', 'd_324', 'd_325', 'd_326', 'd_327', 'd_328', 'd_329', 'd_330', 'd_331', 'd_332', 'd_333', 'd_334', 'd_335', 'd_336', 'd_337', 'd_338', 'd_339', 'd_340', 'd_341', 'd_342', 'd_343', 'd_344', 'd_345', 'd_346', 'd_347', 'd_348', 'd_349', 'd_350', 'd_351', 'd_352', 'd_353', 'd_354', 'd_355', 'd_356', 'd_357', 'd_358', 'd_359', 'd_360', 'd_361', 'd_362', 'd_363', 'd_364', 'd_365', 'd_366', 'd_367', 'd_368', 'd_369', 'd_370', 'd_371', 'd_372', 'd_373', 'd_374', 'd_375', 'd_376', 'd_377', 'd_378', 'd_379', 'd_380', 'd_381', 'd_382', 'd_383', 'd_384', 'd_385', 'd_386', 'd_387', 'd_388', 'd_389', 'd_390', 'd_391', 'd_392', 'd_393', 'd_394', 'd_395', 'd_396', 'd_397', 'd_398', 'd_399', 'd_400', 'd_401', 'd_402', 'd_403', 'd_404', 'd_405', 'd_406', 'd_407', 'd_408', 'd_409', 'd_410', 'd_411', 'd_412', 'd_413', 'd_414', 'd_415', 'd_416', 'd_417', 'd_418', 'd_419', 'd_420', 'd_421', 'd_422', 'd_423', 'd_424', 'd_425', 'd_426', 'd_427', 'd_428', 'd_429', 'd_430', 'd_431', 'd_432', 'd_433', 'd_434', 'd_435', 'd_436', 'd_437', 'd_438', 'd_439', 'd_440', 'd_441', 'd_442', 'd_443', 'd_444', 'd_445', 'd_446', 'd_447', 'd_448', 'd_449', 'd_450', 'd_451', 'd_452', 'd_453', 'd_454', 'd_455', 'd_456', 'd_457', 'd_458', 'd_459', 'd_460', 'd_461', 'd_462', 'd_463', 'd_464', 'd_465', 'd_466', 'd_467', 'd_468', 'd_469', 'd_470', 'd_471', 'd_472', 'd_473', 'd_474', 'd_475', 'd_476', 'd_477', 'd_478', 'd_479', 'd_480', 'd_481', 'd_482', 'd_483', 'd_484', 'd_485', 'd_486', 'd_487', 'd_488', 'd_489', 'd_490', 'd_491', 'd_492', 'd_493', 'd_494', 'd_495', 'd_496', 'd_497', 'd_498', 'd_499', 'd_500', 'd_501', 'd_502', 'd_503', 'd_504', 'd_505', 'd_506', 'd_507', 'd_508', 'd_509', 'd_510', 'd_511', 'd_512', 'd_513', 'd_514', 'd_515', 'd_516', 'd_517', 'd_518', 'd_519', 'd_520', 'd_521', 'd_522', 'd_523', 'd_524', 'd_525', 'd_526', 'd_527', 'd_528', 'd_529', 'd_530', 'd_531', 'd_532', 'd_533', 'd_534', 'd_535', 'd_536', 'd_537', 'd_538', 'd_539', 'd_540', 'd_541', 'd_542', 'd_543', 'd_544', 'd_545', 'd_546', 'd_547', 'd_548', 'd_549', 'd_550', 'd_551', 'd_552', 'd_553', 'd_554', 'd_555', 'd_556', 'd_557', 'd_558', 'd_559', 'd_560', 'd_561', 'd_562', 'd_563', 'd_564', 'd_565', 'd_566', 'd_567', 'd_568', 'd_569', 'd_570', 'd_571', 'd_572', 'd_573', 'd_574', 'd_575', 'd_576', 'd_577', 'd_578', 'd_579', 'd_580', 'd_581', 'd_582', 'd_583', 'd_584', 'd_585', 'd_586', 'd_587', 'd_588', 'd_589', 'd_590', 'd_591', 'd_592', 'd_593', 'd_594', 'd_595', 'd_596', 'd_597', 'd_598', 'd_599', 'd_600', 'd_601', 'd_602', 'd_603', 'd_604', 'd_605', 'd_606', 'd_607', 'd_608', 'd_609', 'd_610', 'd_611', 'd_612', 'd_613', 'd_614', 'd_615', 'd_616', 'd_617', 'd_618', 'd_619', 'd_620', 'd_621', 'd_622', 'd_623', 'd_624', 'd_625', 'd_626', 'd_627', 'd_628', 'd_629', 'd_630', 'd_631', 'd_632', 'd_633', 'd_634', 'd_635', 'd_636', 'd_637', 'd_638', 'd_639', 'd_640', 'd_641', 'd_642', 'd_643', 'd_644', 'd_645', 'd_646', 'd_647', 'd_648', 'd_649', 'd_650', 'd_651', 'd_652', 'd_653', 'd_654', 'd_655', 'd_656', 'd_657', 'd_658', 'd_659', 'd_660', 'd_661', 'd_662', 'd_663', 'd_664', 'd_665', 'd_666', 'd_667', 'd_668', 'd_669', 'd_670', 'd_671', 'd_672', 'd_673', 'd_674', 'd_675', 'd_676', 'd_677', 'd_678', 'd_679', 'd_680', 'd_681', 'd_682', 'd_683', 'd_684', 'd_685', 'd_686', 'd_687', 'd_688', 'd_689', 'd_690', 'd_691', 'd_692', 'd_693', 'd_694', 'd_695', 'd_696', 'd_697', 'd_698', 'd_699', 'd_700', 'd_701', 'd_702', 'd_703', 'd_704', 'd_705', 'd_706', 'd_707', 'd_708', 'd_709', 'd_710', 'd_711', 'd_712', 'd_713', 'd_714', 'd_715', 'd_716', 'd_717', 'd_718', 'd_719', 'd_720', 'd_721', 'd_722', 'd_723', 'd_724', 'd_725', 'd_726', 'd_727', 'd_728', 'd_729', 'd_730', 'd_731', 'd_732', 'd_733', 'd_734', 'd_735', 'd_736', 'd_737', 'd_738', 'd_739', 'd_740', 'd_741', 'd_742', 'd_743', 'd_744', 'd_745', 'd_746', 'd_747', 'd_748', 'd_749', 'd_750', 'd_751', 'd_752', 'd_753', 'd_754', 'd_755', 'd_756', 'd_757', 'd_758', 'd_759', 'd_760', 'd_761', 'd_762', 'd_763', 'd_764', 'd_765', 'd_766', 'd_767', 'd_768', 'd_769', 'd_770', 'd_771', 'd_772', 'd_773', 'd_774', 'd_775', 'd_776', 'd_777', 'd_778', 'd_779', 'd_780', 'd_781', 'd_782', 'd_783', 'd_784', 'd_785', 'd_786', 'd_787', 'd_788', 'd_789', 'd_790', 'd_791', 'd_792', 'd_793', 'd_794', 'd_795', 'd_796', 'd_797', 'd_798', 'd_799', 'd_800', 'd_801', 'd_802', 'd_803', 'd_804', 'd_805', 'd_806', 'd_807', 'd_808', 'd_809', 'd_810', 'd_811', 'd_812', 'd_813', 'd_814', 'd_815', 'd_816', 'd_817', 'd_818', 'd_819', 'd_820', 'd_821', 'd_822', 'd_823', 'd_824', 'd_825', 'd_826', 'd_827', 'd_828', 'd_829', 'd_830', 'd_831', 'd_832', 'd_833', 'd_834', 'd_835', 'd_836', 'd_837', 'd_838', 'd_839', 'd_840', 'd_841', 'd_842', 'd_843', 'd_844', 'd_845', 'd_846', 'd_847', 'd_848', 'd_849', 'd_850', 'd_851', 'd_852', 'd_853', 'd_854', 'd_855', 'd_856', 'd_857', 'd_858', 'd_859', 'd_860', 'd_861', 'd_862', 'd_863', 'd_864', 'd_865', 'd_866', 'd_867', 'd_868', 'd_869', 'd_870', 'd_871', 'd_872', 'd_873', 'd_874', 'd_875', 'd_876', 'd_877', 'd_878', 'd_879', 'd_880', 'd_881', 'd_882', 'd_883', 'd_884', 'd_885', 'd_886', 'd_887', 'd_888', 'd_889', 'd_890', 'd_891', 'd_892', 'd_893', 'd_894', 'd_895', 'd_896', 'd_897', 'd_898', 'd_899', 'd_900', 'd_901', 'd_902', 'd_903', 'd_904', 'd_905', 'd_906', 'd_907', 'd_908', 'd_909', 'd_910', 'd_911', 'd_912', 'd_913', 'd_914', 'd_915', 'd_916', 'd_917', 'd_918', 'd_919', 'd_920', 'd_921', 'd_922', 'd_923', 'd_924', 'd_925', 'd_926', 'd_927', 'd_928', 'd_929', 'd_930', 'd_931', 'd_932', 'd_933', 'd_934', 'd_935', 'd_936', 'd_937', 'd_938', 'd_939', 'd_940', 'd_941', 'd_942', 'd_943', 'd_944', 'd_945', 'd_946', 'd_947', 'd_948', 'd_949', 'd_950', 'd_951', 'd_952', 'd_953', 'd_954', 'd_955', 'd_956', 'd_957', 'd_958', 'd_959', 'd_960', 'd_961', 'd_962', 'd_963', 'd_964', 'd_965', 'd_966', 'd_967', 'd_968', 'd_969', 'd_970', 'd_971', 'd_972', 'd_973', 'd_974', 'd_975', 'd_976', 'd_977', 'd_978', 'd_979', 'd_980', 'd_981', 'd_982', 'd_983', 'd_984', 'd_985', 'd_986', 'd_987', 'd_988', 'd_989', 'd_990', 'd_991', 'd_992', 'd_993', 'd_994', 'd_995', 'd_996', 'd_997', 'd_998', 'd_999', 'd_1000', 'd_1001', 'd_1002', 'd_1003', 'd_1004', 'd_1005', 'd_1006', 'd_1007', 'd_1008', 'd_1009', 'd_1010', 'd_1011', 'd_1012', 'd_1013', 'd_1014', 'd_1015', 'd_1016', 'd_1017', 'd_1018', 'd_1019', 'd_1020', 'd_1021', 'd_1022', 'd_1023', 'd_1024', 'd_1025', 'd_1026', 'd_1027', 'd_1028', 'd_1029', 'd_1030', 'd_1031', 'd_1032', 'd_1033', 'd_1034', 'd_1035', 'd_1036', 'd_1037', 'd_1038', 'd_1039', 'd_1040', 'd_1041', 'd_1042', 'd_1043', 'd_1044', 'd_1045', 'd_1046', 'd_1047', 'd_1048', 'd_1049', 'd_1050', 'd_1051', 'd_1052', 'd_1053', 'd_1054', 'd_1055', 'd_1056', 'd_1057', 'd_1058', 'd_1059', 'd_1060', 'd_1061', 'd_1062', 'd_1063', 'd_1064', 'd_1065', 'd_1066', 'd_1067', 'd_1068', 'd_1069', 'd_1070', 'd_1071', 'd_1072', 'd_1073', 'd_1074', 'd_1075', 'd_1076', 'd_1077', 'd_1078', 'd_1079', 'd_1080', 'd_1081', 'd_1082', 'd_1083', 'd_1084', 'd_1085', 'd_1086', 'd_1087', 'd_1088', 'd_1089', 'd_1090', 'd_1091', 'd_1092', 'd_1093', 'd_1094', 'd_1095', 'd_1096', 'd_1097', 'd_1098', 'd_1099', 'd_1100', 'd_1101', 'd_1102', 'd_1103', 'd_1104', 'd_1105', 'd_1106', 'd_1107', 'd_1108', 'd_1109', 'd_1110', 'd_1111', 'd_1112', 'd_1113', 'd_1114', 'd_1115', 'd_1116', 'd_1117', 'd_1118', 'd_1119', 'd_1120', 'd_1121', 'd_1122', 'd_1123', 'd_1124', 'd_1125', 'd_1126', 'd_1127', 'd_1128', 'd_1129', 'd_1130', 'd_1131', 'd_1132', 'd_1133', 'd_1134', 'd_1135', 'd_1136', 'd_1137', 'd_1138', 'd_1139', 'd_1140', 'd_1141', 'd_1142', 'd_1143', 'd_1144', 'd_1145', 'd_1146', 'd_1147', 'd_1148', 'd_1149', 'd_1150', 'd_1151', 'd_1152', 'd_1153', 'd_1154', 'd_1155', 'd_1156', 'd_1157', 'd_1158', 'd_1159', 'd_1160', 'd_1161', 'd_1162', 'd_1163', 'd_1164', 'd_1165', 'd_1166', 'd_1167', 'd_1168', 'd_1169', 'd_1170', 'd_1171', 'd_1172', 'd_1173', 'd_1174', 'd_1175', 'd_1176', 'd_1177', 'd_1178', 'd_1179', 'd_1180', 'd_1181', 'd_1182', 'd_1183', 'd_1184', 'd_1185', 'd_1186', 'd_1187', 'd_1188', 'd_1189', 'd_1190', 'd_1191', 'd_1192', 'd_1193', 'd_1194', 'd_1195', 'd_1196', 'd_1197', 'd_1198', 'd_1199', 'd_1200', 'd_1201', 'd_1202', 'd_1203', 'd_1204', 'd_1205', 'd_1206', 'd_1207', 'd_1208', 'd_1209', 'd_1210', 'd_1211', 'd_1212', 'd_1213', 'd_1214', 'd_1215', 'd_1216', 'd_1217', 'd_1218', 'd_1219', 'd_1220', 'd_1221', 'd_1222', 'd_1223', 'd_1224', 'd_1225', 'd_1226', 'd_1227', 'd_1228', 'd_1229', 'd_1230', 'd_1231', 'd_1232', 'd_1233', 'd_1234', 'd_1235', 'd_1236', 'd_1237', 'd_1238', 'd_1239', 'd_1240', 'd_1241', 'd_1242', 'd_1243', 'd_1244', 'd_1245', 'd_1246', 'd_1247', 'd_1248', 'd_1249', 'd_1250', 'd_1251', 'd_1252', 'd_1253', 'd_1254', 'd_1255', 'd_1256', 'd_1257', 'd_1258', 'd_1259', 'd_1260', 'd_1261', 'd_1262', 'd_1263', 'd_1264', 'd_1265', 'd_1266', 'd_1267', 'd_1268', 'd_1269', 'd_1270', 'd_1271', 'd_1272', 'd_1273', 'd_1274', 'd_1275', 'd_1276', 'd_1277', 'd_1278', 'd_1279', 'd_1280', 'd_1281', 'd_1282', 'd_1283', 'd_1284', 'd_1285', 'd_1286', 'd_1287', 'd_1288', 'd_1289', 'd_1290', 'd_1291', 'd_1292', 'd_1293', 'd_1294', 'd_1295', 'd_1296', 'd_1297', 'd_1298', 'd_1299', 'd_1300', 'd_1301', 'd_1302', 'd_1303', 'd_1304', 'd_1305', 'd_1306', 'd_1307', 'd_1308', 'd_1309', 'd_1310', 'd_1311', 'd_1312', 'd_1313', 'd_1314', 'd_1315', 'd_1316', 'd_1317', 'd_1318', 'd_1319', 'd_1320', 'd_1321', 'd_1322', 'd_1323', 'd_1324', 'd_1325', 'd_1326', 'd_1327', 'd_1328', 'd_1329', 'd_1330', 'd_1331', 'd_1332', 'd_1333', 'd_1334', 'd_1335', 'd_1336', 'd_1337', 'd_1338', 'd_1339', 'd_1340', 'd_1341', 'd_1342', 'd_1343', 'd_1344', 'd_1345', 'd_1346', 'd_1347', 'd_1348', 'd_1349', 'd_1350', 'd_1351', 'd_1352', 'd_1353', 'd_1354', 'd_1355', 'd_1356', 'd_1357', 'd_1358', 'd_1359', 'd_1360', 'd_1361', 'd_1362', 'd_1363', 'd_1364', 'd_1365', 'd_1366', 'd_1367', 'd_1368', 'd_1369', 'd_1370', 'd_1371', 'd_1372', 'd_1373', 'd_1374', 'd_1375', 'd_1376', 'd_1377', 'd_1378', 'd_1379', 'd_1380', 'd_1381', 'd_1382', 'd_1383', 'd_1384', 'd_1385', 'd_1386', 'd_1387', 'd_1388', 'd_1389', 'd_1390', 'd_1391', 'd_1392', 'd_1393', 'd_1394', 'd_1395', 'd_1396', 'd_1397', 'd_1398', 'd_1399', 'd_1400', 'd_1401', 'd_1402', 'd_1403', 'd_1404', 'd_1405', 'd_1406', 'd_1407', 'd_1408', 'd_1409', 'd_1410', 'd_1411', 'd_1412', 'd_1413', 'd_1414', 'd_1415', 'd_1416', 'd_1417', 'd_1418', 'd_1419', 'd_1420', 'd_1421', 'd_1422', 'd_1423', 'd_1424', 'd_1425', 'd_1426', 'd_1427', 'd_1428', 'd_1429', 'd_1430', 'd_1431', 'd_1432', 'd_1433', 'd_1434', 'd_1435', 'd_1436', 'd_1437', 'd_1438', 'd_1439', 'd_1440', 'd_1441', 'd_1442', 'd_1443', 'd_1444', 'd_1445', 'd_1446', 'd_1447', 'd_1448', 'd_1449', 'd_1450', 'd_1451', 'd_1452', 'd_1453', 'd_1454', 'd_1455', 'd_1456', 'd_1457', 'd_1458', 'd_1459', 'd_1460', 'd_1461', 'd_1462', 'd_1463', 'd_1464', 'd_1465', 'd_1466', 'd_1467', 'd_1468', 'd_1469', 'd_1470', 'd_1471', 'd_1472', 'd_1473', 'd_1474', 'd_1475', 'd_1476', 'd_1477', 'd_1478', 'd_1479', 'd_1480', 'd_1481', 'd_1482', 'd_1483', 'd_1484', 'd_1485', 'd_1486', 'd_1487', 'd_1488', 'd_1489', 'd_1490', 'd_1491', 'd_1492', 'd_1493', 'd_1494', 'd_1495', 'd_1496', 'd_1497', 'd_1498', 'd_1499', 'd_1500', 'd_1501', 'd_1502', 'd_1503', 'd_1504', 'd_1505', 'd_1506', 'd_1507', 'd_1508', 'd_1509', 'd_1510', 'd_1511', 'd_1512', 'd_1513', 'd_1514', 'd_1515', 'd_1516', 'd_1517', 'd_1518', 'd_1519', 'd_1520', 'd_1521', 'd_1522', 'd_1523', 'd_1524', 'd_1525', 'd_1526', 'd_1527', 'd_1528', 'd_1529', 'd_1530', 'd_1531', 'd_1532', 'd_1533', 'd_1534', 'd_1535', 'd_1536', 'd_1537', 'd_1538', 'd_1539', 'd_1540', 'd_1541', 'd_1542', 'd_1543', 'd_1544', 'd_1545', 'd_1546', 'd_1547', 'd_1548', 'd_1549', 'd_1550', 'd_1551', 'd_1552', 'd_1553', 'd_1554', 'd_1555', 'd_1556', 'd_1557', 'd_1558', 'd_1559', 'd_1560', 'd_1561', 'd_1562', 'd_1563', 'd_1564', 'd_1565', 'd_1566', 'd_1567', 'd_1568', 'd_1569', 'd_1570', 'd_1571', 'd_1572', 'd_1573', 'd_1574', 'd_1575', 'd_1576', 'd_1577', 'd_1578', 'd_1579', 'd_1580', 'd_1581', 'd_1582', 'd_1583', 'd_1584', 'd_1585', 'd_1586', 'd_1587', 'd_1588', 'd_1589', 'd_1590', 'd_1591', 'd_1592', 'd_1593', 'd_1594', 'd_1595', 'd_1596', 'd_1597', 'd_1598', 'd_1599', 'd_1600', 'd_1601', 'd_1602', 'd_1603', 'd_1604', 'd_1605', 'd_1606', 'd_1607', 'd_1608', 'd_1609', 'd_1610', 'd_1611', 'd_1612', 'd_1613', 'd_1614', 'd_1615', 'd_1616', 'd_1617', 'd_1618', 'd_1619', 'd_1620', 'd_1621', 'd_1622', 'd_1623', 'd_1624', 'd_1625', 'd_1626', 'd_1627', 'd_1628', 'd_1629', 'd_1630', 'd_1631', 'd_1632', 'd_1633', 'd_1634', 'd_1635', 'd_1636', 'd_1637', 'd_1638', 'd_1639', 'd_1640', 'd_1641', 'd_1642', 'd_1643', 'd_1644', 'd_1645', 'd_1646', 'd_1647', 'd_1648', 'd_1649', 'd_1650', 'd_1651', 'd_1652', 'd_1653', 'd_1654', 'd_1655', 'd_1656', 'd_1657', 'd_1658', 'd_1659', 'd_1660', 'd_1661', 'd_1662', 'd_1663', 'd_1664', 'd_1665', 'd_1666', 'd_1667', 'd_1668', 'd_1669', 'd_1670', 'd_1671', 'd_1672', 'd_1673', 'd_1674', 'd_1675', 'd_1676', 'd_1677', 'd_1678', 'd_1679', 'd_1680', 'd_1681', 'd_1682', 'd_1683', 'd_1684', 'd_1685', 'd_1686', 'd_1687', 'd_1688', 'd_1689', 'd_1690', 'd_1691', 'd_1692', 'd_1693', 'd_1694', 'd_1695', 'd_1696', 'd_1697', 'd_1698', 'd_1699', 'd_1700', 'd_1701', 'd_1702', 'd_1703', 'd_1704', 'd_1705', 'd_1706', 'd_1707', 'd_1708', 'd_1709', 'd_1710', 'd_1711', 'd_1712', 'd_1713', 'd_1714', 'd_1715', 'd_1716', 'd_1717', 'd_1718', 'd_1719', 'd_1720', 'd_1721', 'd_1722', 'd_1723', 'd_1724', 'd_1725', 'd_1726', 'd_1727', 'd_1728', 'd_1729', 'd_1730', 'd_1731', 'd_1732', 'd_1733', 'd_1734', 'd_1735', 'd_1736', 'd_1737', 'd_1738', 'd_1739', 'd_1740', 'd_1741', 'd_1742', 'd_1743', 'd_1744', 'd_1745', 'd_1746', 'd_1747', 'd_1748', 'd_1749', 'd_1750', 'd_1751', 'd_1752', 'd_1753', 'd_1754', 'd_1755', 'd_1756', 'd_1757', 'd_1758', 'd_1759', 'd_1760', 'd_1761', 'd_1762', 'd_1763', 'd_1764', 'd_1765', 'd_1766', 'd_1767', 'd_1768', 'd_1769', 'd_1770', 'd_1771', 'd_1772', 'd_1773', 'd_1774', 'd_1775', 'd_1776', 'd_1777', 'd_1778', 'd_1779', 'd_1780', 'd_1781', 'd_1782', 'd_1783', 'd_1784', 'd_1785', 'd_1786', 'd_1787', 'd_1788', 'd_1789', 'd_1790', 'd_1791', 'd_1792', 'd_1793', 'd_1794', 'd_1795', 'd_1796', 'd_1797', 'd_1798', 'd_1799', 'd_1800', 'd_1801', 'd_1802', 'd_1803', 'd_1804', 'd_1805', 'd_1806', 'd_1807', 'd_1808', 'd_1809', 'd_1810', 'd_1811', 'd_1812', 'd_1813', 'd_1814', 'd_1815', 'd_1816', 'd_1817', 'd_1818', 'd_1819', 'd_1820', 'd_1821', 'd_1822', 'd_1823', 'd_1824', 'd_1825', 'd_1826', 'd_1827', 'd_1828', 'd_1829', 'd_1830', 'd_1831', 'd_1832', 'd_1833', 'd_1834', 'd_1835', 'd_1836', 'd_1837', 'd_1838', 'd_1839', 'd_1840', 'd_1841', 'd_1842', 'd_1843', 'd_1844', 'd_1845', 'd_1846', 'd_1847', 'd_1848', 'd_1849', 'd_1850', 'd_1851', 'd_1852', 'd_1853', 'd_1854', 'd_1855', 'd_1856', 'd_1857', 'd_1858', 'd_1859', 'd_1860', 'd_1861', 'd_1862', 'd_1863', 'd_1864', 'd_1865', 'd_1866', 'd_1867', 'd_1868', 'd_1869', 'd_1870', 'd_1871', 'd_1872', 'd_1873', 'd_1874', 'd_1875', 'd_1876', 'd_1877', 'd_1878', 'd_1879', 'd_1880', 'd_1881', 'd_1882', 'd_1883', 'd_1884', 'd_1885', 'd_1886', 'd_1887', 'd_1888', 'd_1889', 'd_1890', 'd_1891', 'd_1892', 'd_1893', 'd_1894', 'd_1895', 'd_1896', 'd_1897', 'd_1898', 'd_1899', 'd_1900', 'd_1901', 'd_1902', 'd_1903', 'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910', 'd_1911', 'd_1912', 'd_1913']

Data Types:
id            str
item_id       str
dept_id       str
cat_id        str
store_id      str
            ...
d_1909      int64
d_1910      int64
d_1911      int64
d_1912      int64
d_1913      int64
Length: 1919, dtype: object

First 5 Rows:

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

==================================================
sample submission Dataset
==================================================
Shape: (60980, 29)

Column Names:
['id', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28']

Data Types:
id       str
F1     int64
F2     int64
F3     int64
F4     int64
F5     int64
F6     int64
F7     int64
F8     int64
F9     int64
F10    int64
F11    int64
F12    int64
F13    int64
F14    int64
F15    int64
F16    int64
F17    int64
F18    int64
F19    int64
F20    int64
F21    int64
F22    int64
F23    int64
F24    int64
F25    int64
F26    int64
F27    int64
F28    int64
dtype: object

First 5 Rows:

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 3. Before Cleaning Analysis

Before cleaning the datasets, we check for missing values, duplicate records, and overall data quality issues.

In [11]:
print("Calendar Dataset")
calendar.info()
print(calendar.columns)
print(calendar.dtypes)
calendar.describe(include="all")

Calendar Dataset
<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 215.5 KB
Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd',
       'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2',
       'snap_CA', 'snap_TX', 'snap_WI'],
      dtype='str')
date              str
wm_yr_wk        int64
weekday           str
wday            int64
month           int64
year            int64
d                 str
event_name_1      str
event_type_1      str
event_name_2      str
event_type_2      str
snap_CA         int64
snap_TX         int64
snap_WI         int64
dtype: object

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
count,1969,1969.000000,1969,1969.000000,1969.000000,1969.000000,1969,162,162,5,5,1969.000000,1969.000000,1969.000000
unique,1969,NaN,7,NaN,NaN,NaN,1969,30,4,4,2,NaN,NaN,NaN
top,2011-01-29,NaN,Saturday,NaN,NaN,NaN,d_1,SuperBowl,Religious,Father's day,Cultural,NaN,NaN,NaN
freq,1,NaN,282,NaN,NaN,NaN,1,6,55,2,4,NaN,NaN,NaN
mean,NaN,11347.086338,NaN,3.997461,6.325546,2013.288471,NaN,NaN,NaN,NaN,NaN,0.330117,0.330117,0.330117
std,NaN,155.277043,NaN,2.001141,3.416864,1.580198,NaN,NaN,NaN,NaN,NaN,0.470374,0.470374,0.470374
min,NaN,11101.000000,NaN,1.000000,1.000000,2011.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
25%,NaN,11219.000000,NaN,2.000000,3.000000,2012.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
50%,NaN,11337.000000,NaN,4.000000,6.000000,2013.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000
75%,NaN,11502.000000,NaN,6.000000,9.000000,2015.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000
max,NaN,11621.000000,NaN,7.000000,12.000000,2016.000000,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000

In [7]:
print("Sales Train Dataset")
sales.head()
sales.info()
print(sales.columns)
print(sales.dtypes)
sales.describe(include="all")

Sales Train Dataset
<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1947 entries, id to d_1941
dtypes: int64(1941), str(6)
memory usage: 452.9 MB
Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4',
       ...
       'd_1932', 'd_1933', 'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938',
       'd_1939', 'd_1940', 'd_1941'],
      dtype='str', length=1947)
id            str
item_id       str
dept_id       str
cat_id        str
store_id      str
            ...
d_1937      int64
d_1938      int64
d_1939      int64
d_1940      int64
d_1941      int64
Length: 1947, dtype: object

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
count,30490,30490,30490,30490,30490,30490,30490.000000,30490.000000,30490.000000,30490.000000,...,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000
unique,30490,3049,7,3,10,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,FOODS_3,FOODS,CA_1,CA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,10,8230,14370,3049,12196,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.070220,1.041292,0.780026,0.833454,...,1.445490,1.781174,1.965267,1.389374,1.271794,1.216661,1.212299,1.395605,1.689669,1.782158
std,NaN,NaN,NaN,NaN,NaN,NaN,5.126689,5.365468,3.667454,4.415141,...,3.656824,4.426550,4.706284,3.313292,3.126178,3.000348,2.955910,3.514318,4.089208,4.284356
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,360.000000,436.000000,207.000000,323.000000,...,143.000000,156.000000,187.000000,98.000000,90.000000,77.000000,84.000000,110.000000,156.000000,117.000000

In [8]:
print("Sales Validation Dataset")
sales_val.head()
sales_val.info()
print(sales_val.columns)
print(sales.dtypes)
sales_val.describe(include="all")

Sales Validation Dataset
<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 446.4 MB
Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4',
       ...
       'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910',
       'd_1911', 'd_1912', 'd_1913'],
      dtype='str', length=1919)
id            str
item_id       str
dept_id       str
cat_id        str
store_id      str
            ...
d_1937      int64
d_1938      int64
d_1939      int64
d_1940      int64
d_1941      int64
Length: 1947, dtype: object

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
count,30490,30490,30490,30490,30490,30490,30490.000000,30490.000000,30490.000000,30490.000000,...,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000,30490.000000
unique,30490,3049,7,3,10,3,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,FOODS_3,FOODS,CA_1,CA,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,10,8230,14370,3049,12196,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.070220,1.041292,0.780026,0.833454,...,1.370581,1.586159,1.693670,1.248245,1.232207,1.159167,1.149000,1.328862,1.605838,1.633158
std,NaN,NaN,NaN,NaN,NaN,NaN,5.126689,5.365468,3.667454,4.415141,...,3.740017,4.097191,4.359809,3.276925,3.125471,2.876026,2.950364,3.358012,4.089422,3.812248
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,360.000000,436.000000,207.000000,323.000000,...,129.000000,160.000000,204.000000,98.000000,100.000000,88.000000,77.000000,141.000000,171.000000,130.000000

In [9]:
print("Sell Prices Dataset")
sell_prices.head()
sell_prices.info()
print(sell_prices.columns)
print(sell_prices.dtypes)
sell_prices.describe(include="all")

Sell Prices Dataset
<class 'pandas.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    str
 1   item_id     str
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 208.8 MB
Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price'], dtype='str')
store_id          str
item_id           str
wm_yr_wk        int64
sell_price    float64
dtype: object

       store_id        item_id      wm_yr_wk    sell_price
count   6841121        6841121  6.841121e+06  6.841121e+06
unique       10           3049           NaN           NaN
top        TX_2  HOBBIES_1_010           NaN           NaN
freq     701214           2820           NaN           NaN
mean        NaN            NaN  1.138294e+04  4.410952e+00
std         NaN            NaN  1.486100e+02  3.408814e+00
min         NaN            NaN  1.110100e+04  1.000000e-02
25%         NaN            NaN  1.124700e+04  2.180000e+00
50%         NaN            NaN  1.141100e+04  3.470000e+00
75%         NaN            NaN  1.151700e+04  5.840000e+00
max         NaN            NaN  1.162100e+04  1.073200e+02

In [12]:
print("Sample Submission Dataset")
sample.head()
sample.info()

Sample Submission Dataset
<class 'pandas.DataFrame'>
RangeIndex: 60980 entries, 0 to 60979
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      60980 non-null  str
 1   F1      60980 non-null  int64
 2   F2      60980 non-null  int64
 3   F3      60980 non-null  int64
 4   F4      60980 non-null  int64
 5   F5      60980 non-null  int64
 6   F6      60980 non-null  int64
 7   F7      60980 non-null  int64
 8   F8      60980 non-null  int64
 9   F9      60980 non-null  int64
 10  F10     60980 non-null  int64
 11  F11     60980 non-null  int64
 12  F12     60980 non-null  int64
 13  F13     60980 non-null  int64
 14  F14     60980 non-null  int64
 15  F15     60980 non-null  int64
 16  F16     60980 non-null  int64
 17  F17     60980 non-null  int64
 18  F18     60980 non-null  int64
 19  F19     60980 non-null  int64
 20  F20     60980 non-null  int64
 21  F21     60980 non-null  int64
 22  F22     60980 non-null  int64
 23  F23     60980 non-null  int64
 24  F24     60980 non-null  int64
 25  F25     60980 non-null  int64
 26  F26     60980 non-null  int64
 27  F27     60980 non-null  int64
 28  F28     60980 non-null  int64
dtypes: int64(28), str(1)
memory usage: 13.5 MB

## Data Cleaning

The following cleaning steps were performed:
- Standardized column names.
- Removed duplicate records.
- Removed extra spaces from text columns.
- Converted date columns into proper datetime format.

In [18]:
def clean_data(df):
    # Standardize column names
    df.columns = df.columns.str.lower().str.strip()

    # Remove duplicate rows
    df = df.drop_duplicates()

    # Remove extra spaces from text columns
    text_columns = df.select_dtypes(include="object").columns
    for col in text_columns:
        df[col] = df[col].str.strip()

    return df

In [20]:
calendar = clean_data(calendar)
sales = clean_data(sales)
sales_val = clean_data(sales_val)
sell_prices = clean_data(sell_prices)
sample = clean_data(sample)

C:\Users\priya\AppData\Local\Temp\ipykernel_10372\2459745136.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\priya\AppData\Local\Temp\ipykernel_10372\2459745136.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\priya\AppData\Local\Temp\ipykernel_10372\2459745136.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\priya\AppData\Local\Temp\ipykernel_10372\2459745136.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns
C:\Users\priya\AppData\Local\Temp\ipykernel_10372\2459745136.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

## After Cleaning

This section verifies the datasets after cleaning to ensure that the cleaning steps were applied successfully.

In [21]:
calendar.head()
calendar.info()
print(calendar.columns)

sales.head()
sales.info()
print(sales.columns)

sales_val.head()
sales_val.info()
print(sales_val.columns)

sell_prices.head()
sell_prices.info()
print(sell_prices.columns)

sample.head()
sample.info()
print(sample.columns)

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   datetime64[us]
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int32
 5   year          1969 non-null   int32
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_ca       1969 non-null   int64
 12  snap_tx       1969 non-null   int64
 13  snap_wi       1969 non-null   int64
 14  week          1969 non-null   int64
 15  day_of_week   1969 non-null   str
 16  day           1969 non-null   int32
 17  day_of_year   1969 non-null   int32
 18  quarter       1969 non-null   int32
 19  is_weekend    1969 non-null   bool
dtypes: bool(1), datetime64[us](1), int32(5), int64(6), str(7)
memory usage: 255.9 KB
Index(['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd',
       'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2',
       'snap_ca', 'snap_tx', 'snap_wi', 'week', 'day_of_week', 'day',
       'day_of_year', 'quarter', 'is_weekend'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1947 entries, id to d_1941
dtypes: int64(1941), str(6)
memory usage: 452.9 MB
Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4',
       ...
       'd_1932', 'd_1933', 'd_1934', 'd_1935', 'd_1936', 'd_1937', 'd_1938',
       'd_1939', 'd_1940', 'd_1941'],
      dtype='str', length=1947)
<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 446.4 MB
Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'd_1',
       'd_2', 'd_3', 'd_4',
       ...
       'd_1904', 'd_1905', 'd_1906', 'd_1907', 'd_1908', 'd_1909', 'd_1910',
       'd_1911', 'd_1912', 'd_1913'],
      dtype='str', length=1919)
<class 'pandas.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    str
 1   item_id     str
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 208.8 MB
Index(['store_id', 'item_id', 'wm_yr_wk', 'sell_price'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 60980 entries, 0 to 60979
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      60980 non-null  str
 1   f1      60980 non-null  int64
 2   f2      60980 non-null  int64
 3   f3      60980 non-null  int64
 4   f4      60980 non-null  int64
 5   f5      60980 non-null  int64
 6   f6      60980 non-null  int64
 7   f7      60980 non-null  int64
 8   f8      60980 non-null  int64
 9   f9      60980 non-null  int64
 10  f10     60980 non-null  int64
 11  f11     60980 non-null  int64
 12  f12     60980 non-null  int64
 13  f13     60980 non-null  int64
 14  f14     60980 non-null  int64
 15  f15     60980 non-null  int64
 16  f16     60980 non-null  int64
 17  f17     60980 non-null  int64
 18  f18     60980 non-null  int64
 19  f19     60980 non-null  int64
 20  f20     60980 non-null  int64
 21  f21     60980 non-null  int64
 22  f22     60980 non-null  int64
 23  f23     60980 non-null  int64
 24  f24     60980 non-null  int64
 25  f25     60980 non-null  int64
 26  f26     60980 non-null  int64
 27  f27     60980 non-null  int64
 28  f28     60980 non-null  int64
dtypes: int64(28), str(1)
memory usage: 13.5 MB
Index(['id', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10',
       'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20',
       'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28'],
      dtype='str')

## Data Cleaning Decisions

The following cleaning steps were performed:

- Checked dataset dimensions and data types.
- Corrected inconsistent data formats.
- Renamed columns where necessary for better readability.

## add usefull Date Features

In [16]:
# Convert date column to datetime format
calendar['date'] = pd.to_datetime(calendar['date'])

# Create useful date features
calendar['year'] = calendar['date'].dt.year
calendar['month'] = calendar['date'].dt.month
calendar['week'] = calendar['date'].dt.isocalendar().week.astype(int)
calendar['day'] = calendar['date'].dt.day
calendar['day_of_week'] = calendar['date'].dt.day_name()
calendar['day_of_year'] = calendar['date'].dt.dayofyear
calendar['quarter'] = calendar['date'].dt.quarter
calendar['is_weekend'] = calendar['date'].dt.dayofweek >= 5

# Check new features
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,week,day_of_week,day,day_of_year,quarter,is_weekend
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0,4,Saturday,29,29,1,True
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0,4,Sunday,30,30,1,True
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0,5,Monday,31,31,1,False
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0,5,Tuesday,1,32,1,False
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1,5,Wednesday,2,33,1,False

## Feature Engineering

Created new date-based features from the `date` column to support time-series analysis and identify seasonal patterns.

## saved clean files

In [22]:
calendar.to_csv("../data/processed/calendar_cleaned.csv", index=False)

sales_val.to_csv(
    "../data/processed/sales_train_validation_cleaned.csv",
    index=False
)

sales.to_csv(
    "../data/processed/sales_train_evaluation_cleaned.csv",
    index=False
)

sell_prices.to_csv(
    "../data/processed/sell_prices_cleaned.csv",
    index=False
)

sample.to_csv(
    "../data/processed/sample_submission_cleaned.csv",
    index=False
)

In [23]:
calendar = calendar.convert_dtypes()

for col in calendar.select_dtypes(include="object"):
    calendar[col] = calendar[col].astype("category")

In [24]:
sales_val= sales_val.convert_dtypes()

for col in sales_val.select_dtypes(include="object"):
    sales_val[col] = sales_val[col].astype("category")

In [25]:
sales = sales.convert_dtypes()

for col in sales.select_dtypes(include="object"):
    sales[col] = sales[col].astype("category")

In [26]:
sell_prices = sell_prices.convert_dtypes()

for col in sell_prices.select_dtypes(include="object"):
    sell_prices[col] = sell_prices[col].astype("category")

    sample = sample.convert_dtypes()

for col in sample.select_dtypes(include="object"):
    sample[col] = sample[col].astype("category")

C:\Users\priya\AppData\Local\Temp\ipykernel_10372\2593841500.py:8: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in sample.select_dtypes(include="object"):

In [27]:
calendar.to_csv(
    "../data/processed/calendar_cleaned.csv.gz",
    index=False,
    compression="gzip"
)

sales_val.to_csv(
    "../data/processed/sales_train_validation_cleaned.csv.gz",
    index=False,
    compression="gzip"
)

sales.to_csv(
    "../data/processed/sales_train_evaluation_cleaned.csv.gz",
    index=False,
    compression="gzip"
)

sell_prices.to_csv(
    "../data/processed/sell_prices_cleaned.csv.gz",
    index=False,
    compression="gzip"
)

sample.to_csv(
    "../data/processed/sample_submission_cleaned.csv.gz",
    index=False,
    compression="gzip"
)

In [28]:
import os

files = [
    "../data/processed/calendar_cleaned.csv.gz",
    "../data/processed/sales_train_validation_cleaned.csv.gz",
    "../data/processed/sales_train_evaluation_cleaned.csv.gz",
    "../data/processed/sell_prices_cleaned.csv.gz",
    "../data/processed/sample_submission_cleaned.csv.gz"
]

for file in files:
    size = os.path.getsize(file) / (1024 * 1024)
    print(f"{file}: {size:.2f} MB")

../data/processed/calendar_cleaned.csv.gz: 0.03 MB
../data/processed/sales_train_validation_cleaned.csv.gz: 14.34 MB
../data/processed/sales_train_evaluation_cleaned.csv.gz: 14.62 MB
../data/processed/sell_prices_cleaned.csv.gz: 14.42 MB
../data/processed/sample_submission_cleaned.csv.gz: 0.16 MB

# Final Cleaning Summary

Completed tasks:

1. Loaded all datasets using project-relative paths.
2. Reviewed dataset structure, shape, columns, and data types.
3. Performed initial data inspection before cleaning.
4. Handled missing values and duplicate records.
5. Standardized data formats and cleaned inconsistencies.
6. Created new date-based features:
   - Year
   - Month
   - Week
   - Day of Week
7. Saved all cleaned datasets into the data/processed folder.

The datasets are now cleaned and ready for exploratory data analysis (EDA) and further modeling.